baseurl: ""
safe: false
url: "https://somdev.in"
title: "Somdev Sangwan"
permalink: pretty

description: "Somdev Sangwan (s0md3v)"
author:
  name: Somdev Sangwan
  twitter: s0md3v
# Social handles
social:
  twitter: s0md3v
  github: s0md3v
  linkedin: s0md3v
  instagram: s0md3v

# Required for jekyll-seo-tag
twitter:
  username: s0md3v

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

sass:
  style: compressed

# Default social image
image:
  path: /assets/images/profile.jpg

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - mockups
  - keys.txt
  - .git